In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# create aaray using numpy
# 1d array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row 5 col 


array([[1, 2, 3, 4, 5]])

In [ ]:
arr2 = np.array([[1,2,3,4,5]]) 
arr2.shape

(1, 5)

In [8]:
arr2 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# attributes of numpy array
arr = np.array([[1,2,3], [4,5,6]])

print("array: \n", arr)
print("shape: ", arr.shape)
print("number of dimensions: ", arr.ndim)
print("size (number of elements): ", arr.size)
print("data type: ", arr.dtype)
print("item size (in bytes): ", arr.itemsize)

array: 
 [[1 2 3]
 [4 5 6]]
shape:  (2, 3)
number of dimensions:  2
size (number of elements):  6
data type:  int64
item size (in bytes):  8


In [ ]:
# numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition
print("addition: ", arr1+arr2)

# element wise subtraction
print("subtraction: ", arr2-arr1)

# element wise multiplication
print("multiplication: ", arr2*arr1)



addition:  [11 22 33 44 55]
subtraction:  [ 9 18 27 36 45]


In [22]:
# universal function - that applies to entire array
arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sin
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [4]:
# array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
arr[0][0]

np.int64(1)

In [9]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [12]:
arr[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [15]:
arr[1:, 1: 3]

array([[ 6,  7],
       [10, 11]])

In [16]:
# modify array elements
arr[0][0] = 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [17]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [19]:
# statistical concepts
# normalization
# to have a mean of 0 and Standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# normailize the data
normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [20]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# mean
mean = np.mean(data)
print("mean: ", mean)

# median
median = np.median(data)
print("median: ", median)

# standard deviation
std_dev = np.std(data)
print("standard deviation: ", std_dev)

# variance
variance = np.var(data)
print("variance: ", variance)

mean:  5.5
median:  5.5
standard deviation:  2.8722813232690143
variance:  8.25


In [25]:
# logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data > 5


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
data[(data >= 5) & (data <= 8) ]

array([5, 6, 7, 8])