# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [1]:
# 1 - Assignment 1: Array Creation and Manipulation

# 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.


import numpy as np

arr = np.random.randint(1, 21, size=(5,5))

print("Original array: ")
print(arr)

arr[:,2] = 1

print("Moodified array: ")
print(arr)

Original array: 
[[17  9 10  4  6]
 [ 4  9 16 10 12]
 [10  9  3  7 19]
 [ 7  9  8 16 18]
 [ 5  5  8 15 14]]
Moodified array: 
[[17  9  1  4  6]
 [ 4  9  1 10 12]
 [10  9  1  7 19]
 [ 7  9  1 16 18]
 [ 5  5  1 15 14]]


In [6]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.
arr = np.arange(1, 17).reshape(4,4)
print("Original arr: ")
print(arr)

# replace diagonal elements with 0
np.fill_diagonal(arr, 0)
print("Modified arr: ")
print(arr)

Original arr: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modified arr: 
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [ ]:
# Assignment 2: Array Indexing and Slicing

# 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
arr = np.arange(1, 37).reshape(6,6)
print("Original arr: \n", arr)

sub_arr = arr[2:5, 1:4]
print("Sub array: \n", sub_arr)

Original arr: 
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub array: 
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


In [17]:
# 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.
arr = np.random.randint(1,26, size=(5,5))
print("Original arr: \n", arr)

# border elements
border_arr = np.concatenate((arr[0, :], arr[-1, :], arr[1:-1, 0], arr[1:-1, -1]))
print("Border elements: \n", border_arr)

Original arr: 
 [[11  7  5  4 18]
 [ 5 15  5  5  8]
 [12 10 22 16 12]
 [22 22 22 10 13]
 [ 8 20  8 20 16]]
Border elements: 
 [11  7  5  4 18  8 20  8 20 16  5 12 22  8 12 13]


In [ ]:
# Assignment 3: Array Operations

# 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
arr1 = np.random.randint(1, 13, size=(3,4))
arr2 = np.random.randint(1, 13, size=(3,4))
print("arr1: \n", arr1)
print("arr2: \n", arr2)

print("addition: \n", arr1+arr2)
print("subtraction: \n", arr1-arr2)
print("multiplication: \n", arr1*arr2)
print("division: \n", arr1/arr2)

arr1: 
 [[7 4 1 5]
 [9 7 5 2]
 [6 1 2 8]]
arr2: 
 [[ 7  9 11  1]
 [ 4 11 11  3]
 [ 1  2  5  8]]
addition: 
 [[14 13 12  6]
 [13 18 16  5]
 [ 7  3  7 16]]
subtraction: 
 [[  0  -5 -10   4]
 [  5  -4  -6  -1]
 [  5  -1  -3   0]]
multiplication: 
 [[49 36 11  5]
 [36 77 55  6]
 [ 6  2 10 64]]
division: 
 [[1.         0.44444444 0.09090909 5.        ]
 [2.25       0.63636364 0.45454545 0.66666667]
 [6.         0.5        0.4        1.        ]]


In [26]:
# 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
arr = np.arange(1, 17).reshape(4,4)

print("Arr: \n", arr)

print("Row wise sum")
print(np.sum(arr, axis=1))
print("Col wise sum")
print(np.sum(arr, axis=0))

Arr: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum
[10 26 42 58]
Col wise sum
[28 32 36 40]


In [ ]:
# Assignment 4: Statistical Operations

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
arr = np.random.randint(1, 26, size=(5,5))
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))
print("Variance: ", np.var(arr))

Mean:  15.6
Median:  16.0
Standard Deviation:  6.474565622495458
Variance:  41.92


In [37]:
# 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).
arr = np.arange(1, 10).reshape(3,3)
print("Arr: \n", arr)

# normalize the array
mean = np.mean(arr)
std_dev = np.std(arr)
normalized = (arr - mean)/std_dev

print("Normalized array: \n", normalized)
print("Mean of normalized: ", np.mean(normalized))
print("Standard deviation: ", np.std(normalized))

Arr: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array: 
 [[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]
Mean of normalized:  0.0
Standard deviation:  1.0


In [ ]:
# Assignment 5: Broadcasting

# 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
arr = np.random.randint(1, 10, size=(3,3))
row_arr = np.random.randint(1, 10, size=(3,))
print("arr: \n", arr)
print("row_arr: \n", row_arr)
new_arr = arr+row_arr
print("new: \n", new_arr)


arr: 
 [[7 8 1]
 [1 9 8]
 [8 8 1]]
row_arr: 
 [5 7 1]
new: 
 [[12 15  2]
 [ 6 16  9]
 [13 15  2]]


In [19]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.
arr = np.random.randint(1, 17, size=(4,4))
print("arr: \n", arr)

row_arr = np.random.randint(1, 17, size=(4,))

print("1-d arr: \n", row_arr)

new_arr = arr - row_arr[:, np.newaxis]
print("new_arr: \n", new_arr)

arr: 
 [[10  9 16  5]
 [ 9  9  2 10]
 [ 5  8 16  5]
 [11 12  8  3]]
1-d arr: 
 [ 4 12  1  4]
new_arr: 
 [[  6   5  12   1]
 [ -3  -3 -10  -2]
 [  4   7  15   4]
 [  7   8   4  -1]]


In [ ]:
# Assignment 6: Linear Algebra

# 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
arr = np.random.randint(1, 10, size=(3,3))
print("arr: \n", arr)

determinant = np.linalg.det(arr)
inverse = np.linalg.inv(arr)
eigen_values = np.linalg.eigvals(arr)
print("Determinant: ", determinant)
print("Inverse: ", inverse)
print("Eigen value: ", eigen_values)

arr: 
 [[2 8 3]
 [7 2 6]
 [8 2 8]]
Determinant:  -61.99999999999995
Inverse:  [[-0.06451613  0.93548387 -0.67741935]
 [ 0.12903226  0.12903226 -0.14516129]
 [ 0.03225806 -0.96774194  0.83870968]]
Eigen value:  [15.37915612 -4.31371688  0.93456077]


In [7]:
# 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
arr1 = np.random.randint(1, 5, size=(2, 3))
print("arr1: \n", arr1)

arr2 = np.random.randint(1, 5, size=(3, 2))
print("arr2: \n", arr2)

arr3 = np.dot(arr1, arr2)
print("arr3: \n", arr3)

arr1: 
 [[2 4 3]
 [2 1 1]]
arr2: 
 [[1 4]
 [3 4]
 [2 4]]
arr3: 
 [[20 36]
 [ 7 16]]


In [ ]:
# Assignment 7: Advanced Array Manipulation

# 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
arr = np.arange(1, 10).reshape(3,3)
print("Original arr: \n", arr)

print("Shape (1,9): \n", arr.reshape(1, 9))

print("Shape (9,1): \n", arr.reshape(9,1))

Original arr: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape (1,9): 
 [[1 2 3 4 5 6 7 8 9]]
Shape (9,1): 
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [8]:
# 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
arr = np.random.randint(1, 26, size=(5,5))
print("Arr: \n", arr)

flatten = arr.flatten()
print("Flatten arr: \n", flatten)

reshaped = flatten.reshape(5,5)
print("Reshaped: \n", reshaped)

Arr: 
 [[15  8 21  6 16]
 [ 2 15 22 16 11]
 [ 6 21  4 20 12]
 [17 20 17  9 24]
 [ 1 22  5 20 18]]
Flatten arr: 
 [15  8 21  6 16  2 15 22 16 11  6 21  4 20 12 17 20 17  9 24  1 22  5 20
 18]
Reshaped: 
 [[15  8 21  6 16]
 [ 2 15 22 16 11]
 [ 6 21  4 20 12]
 [17 20 17  9 24]
 [ 1 22  5 20 18]]


In [ ]:
# Assignment 8: Fancy Indexing and Boolean Indexing

# 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
arr = np.random.randint(1, 26, size=(5,5))
print("Arr: \n", arr)

print("Elements at corner:")
print(arr[[0, 0, -1, -1], [0, -1, 0, -1]])

Arr: 
 [[ 8  4  6 18 19]
 [13  3 19 15 13]
 [11 14 19 11  5]
 [17 17 16 10 17]
 [23 22 19 14 23]]
Elements at corner:
[ 8 19 23 23]


In [13]:
# 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.
arr = np.random.randint(1, 17, size=(4,4))
print("Arr: \n", arr)

arr[arr > 10] = 10
print("Modified: \n", arr)

Arr: 
 [[ 5 10 14 16]
 [16  6 10 15]
 [ 6 16 15 16]
 [ 8 16 13 13]]
Modified: 
 [[ 5 10 10 10]
 [10  6 10 10]
 [ 6 10 10 10]
 [ 8 10 10 10]]


In [ ]:
# Assignment 9: Structured Arrays

# 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
arr_dtype = np.dtype([
    ('Name', 'U20'), # unicode string of max 20 char
    ('Age', 'i4'), # integer of 4 byte
    ('Weight', 'f4') # float of 4 byte
])

arr = np.array([
    ('Ram', 20, 70.9),
    ('Shyam', 22, 65.3),
    ('Gita', 18, 60.0)
], dtype=arr_dtype)

print("Arr: \n", arr)
print("Sorting arr on age feild: \n", np.sort(arr, order='Age'))

Arr: 
 [('Ram', 20, 70.9) ('Shyam', 22, 65.3) ('Gita', 18, 60. )]
Sorting arr on age feild: 
 [('Gita', 18, 60. ) ('Ram', 20, 70.9) ('Shyam', 22, 65.3)]


In [10]:
# 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
arr_dtype = np.dtype([
    ('x', 'i4'),
    ('y', 'i4')
])

arr = np.array([
    (2, 3),
    (7, 2),
    (1, 1),
    (4, 5),
], dtype=arr_dtype)

print("Arr: \n", arr)


# But you need every point compared with every other point.

# Conceptually, you need something like:

#         P0     P1     P2     P3
# P0      0      d01    d02    d03
# P1      d10    0      d12    d13
# P2      d20    d21    0      d23
# P3      d30    d31    d32    0
# sqrt((x1-x2)**2 + (y1-y2)**2)
eucid_distance = np.sqrt((arr['x'] - arr['x'][:, np.newaxis]) ** 2 + (arr['y'] - arr['y'][:, np.newaxis])**2)
print("Euclidean distance between points: \n", eucid_distance)

Arr: 
 [(2, 3) (7, 2) (1, 1) (4, 5)]
Euclidean distance between points: 
 [[0.         5.09901951 2.23606798 2.82842712]
 [5.09901951 0.         6.08276253 4.24264069]
 [2.23606798 6.08276253 0.         5.        ]
 [2.82842712 4.24264069 5.         0.        ]]


In [16]:
# Assignment 10: Masked Arrays

# 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
arr = np.random.randint(1, 17, size=(4,4))
print("Arr: \n", arr)

# masking - This value exists, but for my calculations, pretend it isn't there
masked_arr = np.ma.masked_greater(arr, 10)
print("Masked arr: \n", arr)

print("Sum of unmasked elements: ", np.ma.sum(masked_arr))

Arr: 
 [[ 6 15 13 13]
 [12  3 14  4]
 [12  7 15  4]
 [ 6 16  1  4]]
Masked arr: 
 [[ 6 15 13 13]
 [12  3 14  4]
 [12  7 15  4]
 [ 6 16  1  4]]
Sum of unmasked elements:  35


In [ ]:
# 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
arr = np.random.randint(1, 10, size=(3,3))
print("Arr: \n", arr)

# create mask - identity matrix 3x3
mask = np.eye(3, dtype=bool)
print(mask)

# masked array
masked_arr = np.ma.masked_array(arr, mask=mask)
print("Masked arr: \n", masked_arr)

mean = masked_arr.mean() # it will only consider non masked element both in num and denum
print("Mean: ", mean)

# filled() means:

# Create a normal array where the masked positions are replaced with the value I provide.
final = masked_arr.filled(mean)
print("Final arr: \n", final) # arr is int type theirfore in o/p it dropped decimal part

Arr: 
 [[6 9 4]
 [1 1 6]
 [4 8 7]]
[[ True False False]
 [False  True False]
 [False False  True]]
Masked arr: 
 [[-- 9 4]
 [1 -- 6]
 [4 8 --]]
Mean:  5.333333333333333
Final arr: 
 [[5 9 4]
 [1 5 6]
 [4 8 5]]
